on:
  push:
    branches: [ '*' ]
    tags: ["*"]
  pull_request:
    branches: [ '*' ]

name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Download dependencies
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: --snapshot --skip-publish --rm-dist

      - name: Test
        run: ./test.sh
        env:
          TR_UPLOAD_TOKEN: VrYKBzKODDZQhzRFLJfNIdDsBalpHc

  release:
    name: Release
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Download dependencies
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
